- name: Copiando console_libraries
  copy:
    src: "/opt/prometheus/console_libraries"
    dest: "/etc/prometheus/"
    owner: prometheus
    group: prometheus
    mode: "0755"
    remote_src: yes

- name: Copiando consoles
  copy:
    src: "/opt/prometheus/consoles"
    dest: "/etc/prometheus/"
    owner: prometheus
    group: prometheus
    mode: "0755"
    remote_src: yes


- name: Copiando arquivo de configuração
  template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: "0755"


- name: Criando arquivo systemd prometheus
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Enable prometheus.service
  systemd:
    name: prometheus
    enabled: yes


- name: Start prometheus.service
  systemd:
    name: prometheus
    state: started
    daemon_reload: yes